#!/bin/sh

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail

k=$(find . -name kustomization.yaml)

for d in $k; do
    echo checking $(dirname $d)
    kustomize build --enable_alpha_plugins $(dirname $d) 2>&1 >/dev/null
done

#end.
