#!/bin/sh

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail

# Let's ignore the secrets...

export KUSTOMIZE_PLUGIN_HOME=/tmp/new_plugin_dir

mkdir -p $KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/
echo '#!/bin/sh' >$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/ksops
chmod +x $KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/ksops

# and check all the sub directories with manifests...
k=$(find . -name kustomization.yaml)

for d in $k; do
    if [[ $(dirname $d) == *overrides* ]]; then
        echo skipping $(dirname $d)
        continue
    fi

    echo checking $(dirname $d)
    kustomize build --enable_alpha_plugins $(dirname $d) 2>&1 >/dev/null
done

#end.
