{
 "title": "Cluster CPU overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total CPU on Cluster (Master)",
   "type": "stat",
   "description": "Total cpu cores available on master nodes.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}"
    }
   ]
  },
  {
   "title": "Total CPU on Cluster (Worker)",
   "type": "stat",
   "description": "Total cpu cores available on worker nodes.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total ResourceQuota CPU Requests",
   "type": "bargauge",
   "description": "CPU Requests alotted via Resource Quotas out of Available Cores on the cluster.\n\nMax value is the total cpu cores on worker nodes (if the cluster has only master nodes, then masters are taken into account instead).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.cpu\"})"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Actual Free Cores (Master Nodes)",
   "type": "bargauge",
   "description": "Cores currently not in use on Master nodes. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.\n\nFormula: \n(Total master CPU capacity) - (Total master CPU requests)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"master\"}))",
     "legendFormat": "Free Cores"
    },
    {
     "expr": "cluster:capacity_cpu_cores:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io=\"master\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Total CPU Limits on Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_limit{cluster=\"$cluster\", resource=\"cpu\"})"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Total ResourceQuota CPU Limits",
   "type": "bargauge",
   "description": "CPU Limits alotted via Resource Quotas out of Available Cores on the cluster.\n\nMax value is the total cpu cores on worker nodes (if the cluster has only master nodes, then masters are taken into account instead).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"limits.cpu\"})"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Actual Free Cores (Workers)",
   "type": "bargauge",
   "description": "Cores currently not in use on Worker nodes. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.\n\nFormula: \n(Total worker CPU capacity) - (Total Worker CPU requests)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - \n\n(sum(\n    kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"} \n    * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"})\n    )",
     "legendFormat": "Free Cores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Total CPU Requests on Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"})"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Free Cores (Master)",
   "type": "graph",
   "description": "Cores currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"master\"}))",
     "legendFormat": "Free Cores"
    }
   ]
  },
  {
   "title": "Free Cores (Workers)",
   "type": "graph",
   "description": "Cores currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    }
   ]
  },
  {
   "title": "Pod CPU Limits by Namespace",
   "type": "barchart",
   "description": "This graph shows the sum of cpu limits scheduled by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(20, sort_desc(sum(kube_pod_resource_limit{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Pod CPU Requests by Namespace",
   "type": "barchart",
   "description": "This graph shows the sum of cpu being requested by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(20, sort_desc(sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU ResourceQuota (Requests) By Namespace",
   "type": "barchart",
   "description": "This graph shows the sum of cpu being requested by resourcequotas. I.e. how much CPU can be requested per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(20, sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.cpu\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU ResourceQuota (Limits) By Namespace",
   "type": "barchart",
   "description": "This graph shows the sum of cpu limits scheduled by resourcequotas. I.e. how much CPU Limits are alotted per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(20, sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"limits.cpu\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total CPU Requests",
   "type": "table",
   "description": "Approximate CPU requests on each node by summing CPU requests on all PENDING and RUNNING pods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace, pod, node) * on (pod, namespace) group_left() (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total CPU Limits",
   "type": "table",
   "description": "Approximate CPU Limits on each node by summing CPU limits on all PENDING and RUNNING pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace, pod, node) * on (pod, namespace) group_left() (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Load Averages by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "1 Min Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(node_load1{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "5 Min Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(node_load5{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) /sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "15 Min Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(node_load15{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}