{
 "title": "Node Compute Resources Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kubelet_node_name, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Limits by Namespace",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"cpu\", node=\"$node\"}) by (namespace, pod)\n    * on (pod, namespace) group_left() \n    (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Requests by Namespace",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\", node=\"$node\"}) by (namespace, pod)\n    * on (pod, namespace) group_left() \n    (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)    \n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Limits by Namespace",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"memory\", node=\"$node\"}) by (namespace, pod)\n    * on (pod, namespace) group_left() \n    (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requests by Namespace",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\", node=\"$node\"}) by (namespace, pod)\n    * on (pod, namespace) group_left() \n    (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}