{
 "title": "Cluster Memory overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Memory on Cluster (Master)",
   "type": "stat",
   "description": "Total Memory available on master nodes.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}"
    }
   ]
  },
  {
   "title": "Total Memory on Cluster (Worker)",
   "type": "stat",
   "description": "Total memory available on worker nodes.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}"
    }
   ]
  },
  {
   "title": "Total ResourceQuota Memory Requests",
   "type": "bargauge",
   "description": "Memory Requests alotted via Resource Quotas out of Available memory on the cluster.\n\nMax value is the total Memory on worker nodes (if the cluster has only master nodes, then masters are taken into account instead).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.memory\"})"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"} OR on() cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"} ",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Actual Free Memory (Master Nodes)",
   "type": "bargauge",
   "description": "Memory currently not in use on Master nodes. This does not take into account ResourceQuotas, rather -- it takes into account memory available for the scheduler to reserve for pods.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"master\"}))",
     "legendFormat": "Free Cores"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io=\"master\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Total Memory Requests on Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"})"
    },
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Total ResourceQuota Memory Limits",
   "type": "bargauge",
   "description": "Memory Limits alotted via Resource Quotas out of Available Memory on the cluster.\n\nMax value is the total Memory on worker nodes (if the cluster has only master nodes, then masters are taken into account instead).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"limits.memory\"})"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"} OR on() cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"} ",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Actual Free Memory (Workers)",
   "type": "bargauge",
   "description": "Memory currently not in use on Worker nodes. This does not take into account ResourceQuotas, rather -- it takes into account memory available for the scheduler to reserve for pods.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - \n(sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Total Memory Limits on Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_limit{cluster=\"$cluster\", resource=\"memory\"})"
    },
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Free Memory (Master)",
   "type": "graph",
   "description": "Memory currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"master\"}))",
     "legendFormat": "Free Cores"
    }
   ]
  },
  {
   "title": "Free Memory (Workers)",
   "type": "graph",
   "description": "Memory currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    }
   ]
  },
  {
   "title": "Pod Memory Limits by Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of Memory limits scheduled by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_resource_limit{cluster=\"$cluster\", resource=\"memory\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Pod Memory Requests by Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of Memory being requested by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory ResourceQuota (Requests) By Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of Memory being requested by resourcequotas. I.e. how much Memory can be requested per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory ResourceQuota (Limits) By Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of Memory limits scheduled by resourcequotas. I.e. how much Memory Limits are alotted per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"limits.memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Memory Requests",
   "type": "table",
   "description": "Approximate Memory requests on each node by summing Memory requests on all PENDING and RUNNING pods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"}) by (namespace, pod, node) * on (pod, namespace) group_left() (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Memory Limits",
   "type": "table",
   "description": "Approximate Memory Limits on each node by summing Memory limits on all PENDING and RUNNING pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"memory\"}) by (namespace, pod, node) * on (pod, namespace) group_left() (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}