{
 "title": "Cluster Storage Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "% of Free Space on Cluster",
   "type": "stat",
   "description": "These metrics are from the space queried from persistent volumes (PVs)",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{cluster=\"$cluster\"}) / sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Space on Cluster",
   "type": "stat",
   "description": "These metrics show used, available, and total PVC space on the cluster. This only takes into account already allocated and bound PVCs. The total PVC space will increase if more PVC's are created on a given cluster.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Available Space"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "PVC usage by namespace",
   "type": "piechart",
   "description": "Shows PersistentVolumeClaims usage by namespace",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Used Space by Cluster",
   "type": "bargauge",
   "description": "A bar gauge to display have storage you have used in comparison to the capacity of your storage.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Capacity/Total"
    }
   ]
  },
  {
   "title": "PV Total Count on Clusters",
   "type": "stat",
   "description": "Total number of PVs per cluster",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (pv_collector_total_pv_count)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Lowest 20 PVCs by capacity remaining",
   "type": "table",
   "description": "This panel shows you the 20 PVC's with the least % of free capacity left",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(20, kubelet_volume_stats_available_bytes{cluster=\"$cluster\"} / kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top 20 Namespace usage on Cluster (File-system)",
   "type": "table",
   "description": "THis panel takes metrics from the containers file ssytem to display the top 20 namespaces suing Filesystem space usage",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(sum(avg_over_time(pod:container_fs_usage_bytes:sum{container=\"\", pod!=\"\"}[5m])) BY (namespace)))"
    },
    { "expr": "container_fs_" }
   ]
  }
 ]
}