{
 "title": "Kubeflow Pipelines (Tekton) - User Perspective",
 "time": { "from": "2021-05-03T04:00:06.354Z", "to": "2021-05-03T06:45:51.383Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pipelinerun",
    "label": "Pipeline run name",
    "query": "label_values(tekton_pipelines_controller_pipelinerun_duration_seconds_sum{exported_namespace=\"kubeflow\"}, pipelinerun)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "\n![](https://avatars.githubusercontent.com/u/33164907?s=200&v=4)"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\",phase=~\"Running|Pending\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Total CPU cores reserved and unused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(scalar(sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"})) - scalar(sum(pod:container_cpu_usage:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}))) / sum(node_cpu_info)"
    }
   ]
  },
  {
   "title": "Duration brakdown",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_pipelinerun_duration_seconds_sum{pipelinerun=\"$pipelinerun\"}",
     "legendFormat": "Controller"
    },
    {
     "expr": "label_replace(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_sum{pipelinerun=\"$pipelinerun\"}, \"taskname\", \"$1\", \"taskrun\", \"$pipelinerun-(.*)\")",
     "legendFormat": "Task: {{taskname}}"
    }
   ]
  },
  {
   "title": "Total memory reserved and unused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(scalar(sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"})) -  scalar(sum(pod:container_memory_usage_bytes:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}))) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "CPU % of request",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "repeat": "kubeflowPod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pod:container_cpu_usage:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}) / on() sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory % of request",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pod:container_memory_usage_bytes:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}) /  on () sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"})",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Total resource consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pod:container_cpu_usage:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\", exported_namespace=\"kubeflow\", exported_pod=~\"$pipelinerun.*\"})",
     "legendFormat": "Effective request"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource=\"cpu\", exported_namespace=\"kubeflow\", exported_pod=~\"$pipelinerun.*\"})",
     "legendFormat": "Effective limit"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pod:container_memory_usage_bytes:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"memory\", exported_namespace=\"kubeflow\", exported_pod=~\"$pipelinerun.*\"})",
     "legendFormat": "Effective request"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource=\"memory\", exported_namespace=\"kubeflow\", exported_pod=~\"$pipelinerun.*\"})",
     "legendFormat": "Effective limit"
    }
   ]
  },
  { "title": "Breakdown per task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage Breakdown",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(pod:container_cpu_usage:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}, \"legend\", \"$1\", \"pod\", \"$pipelinerun-(.*)-pod-.{5}\")",
     "legendFormat": "{{legend}}"
    }
   ]
  },
  {
   "title": "Memory Usage Breakdown",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(pod:container_memory_usage_bytes:sum{namespace=\"kubeflow\",pod=~\"$pipelinerun.*\"}, \"legend\", \"$1\", \"pod\", \"$pipelinerun-(.*)-pod-.{5}\")",
     "legendFormat": "{{legend}}"
    }
   ]
  }
 ]
}