{
 "title": "Cluster Pod Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "moc/smaug,moc/infra,emea/rick,emea/balrog"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods  Aggregated by Phase",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\"} == 1) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Failed pods by namespace",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Failed\"} == 1) by (namespace)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Top 20 Pod count (running) by namespace",
   "type": "barchart",
   "description": "This list excludes openshift namespaces",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(20,sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Running\", namespace!~\"openshift-.*\"} == 1) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top 20 Namespaces by pod restart count",
   "type": "barchart",
   "description": "This only takes into considerations pods scheduled as either Running,Failed,Pending,Succeeded",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "topk(20,sum(sum(kube_pod_container_status_restarts_total{cluster=\"$cluster\",} > 0) by (pod) * on (pod) group_right() (kube_pod_status_phase{cluster=\"$cluster\"} == 1)) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}