{
 "title": "Cluster CPU overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "moc/smaug,moc/infra,emea/rick,emea/balrog"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU on Cluster (Master)",
   "type": "stat",
   "description": "Total cpu cores available on master nodes.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}"
    }
   ]
  },
  {
   "title": "Total CPU on Cluster (Worker)",
   "type": "stat",
   "description": "Total cpu cores available on worker nodes.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}"
    }
   ]
  },
  {
   "title": "Total CPU ResourceQuota",
   "type": "gauge",
   "description": "The total amount of cpu requests that have been requested by ResourceQuotas currently active.\n\nMax value is total cores available on cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.cpu\"})"
    },
    {
     "expr": "cluster:capacity_cpu_cores:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Free Cores (Approx)",
   "type": "gauge",
   "description": "Cores currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    },
    {
     "expr": "cluster:capacity_cpu_cores:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Pod CPU Requests by Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of cpu being requested by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Free Cores (Approx)",
   "type": "graph",
   "description": "Cores currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    }
   ]
  },
  {
   "title": "CPU ResourceQuota By Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of cpu being requested by resourcequotas. I.e. how much CPU can be requested per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.cpu\", prometheus_replica=\"prometheus-k8s-1\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total CPU Requests",
   "type": "table",
   "description": "Approximate CPU requests on each node by summing CPU requests on all PENDING and RUNNING pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace, pod, node) * on (pod, namespace) group_left() (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Load Averages by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "1 Min Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(node_load1{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "5 Min Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(node_load5{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) /sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "15 Min Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(node_load15{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}