{
 "title": "Cluster Memory overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Memory on Cluster (Master)",
   "type": "stat",
   "description": "Total memory available on master nodes.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io=\"master\"}"
    }
   ]
  },
  {
   "title": "Total Memory on Cluster (Worker)",
   "type": "stat",
   "description": "Total memory available on worker nodes.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}"
    }
   ]
  },
  {
   "title": "Total Memory ResourceQuota",
   "type": "gauge",
   "description": "The total amount of memory requests that have been requested by ResourceQuotas currently active.\n\nMax value is total cores available on cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.memory\"})"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Free Memory (Approx)",
   "type": "gauge",
   "description": "Memory currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account memory available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{cluster=~\"$cluster\", label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Pod Memory Requests by Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of memory being requested by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Free Memory (Approx)",
   "type": "timeseries",
   "description": "Memory currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account memory available for the scheduler to reserve for pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{cluster=\"$cluster\", label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\"} * on (node) group_left kube_node_role{cluster=\"$cluster\", role=\"worker\"}))",
     "legendFormat": "Free Cores"
    }
   ]
  },
  {
   "title": "Memory ResourceQuota (Requests) By Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of memory being requested by resourcequotas. I.e. how much memory can be requested per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=\"$cluster\", type=\"hard\", resource=\"requests.memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total CPU Requests",
   "type": "table",
   "description": "Approximate memory requests on each node by summing memory requests on all PENDING and RUNNING pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"}) by (namespace, pod, node) * on (pod, namespace) group_left() (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=~\"Pending|Running\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}