{
 "title": "Node feature discovery",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "moc/smaug,moc/infra,emea/rick,emea/balrog"
   },
   { "name": "flag", "label": "Global flag filter", "query": { "query": "label_names()" } }
  ]
 },
 "panels": [
  { "title": "Filtered by flag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters with support for \"$flag\"",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_feature_node_kubernetes_io_cpu_cpuid_$flag=\"true\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Nodes with support for \"$flag\"",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_feature_node_kubernetes_io_cpu_cpuid_$flag=\"true\"}) by (node, cluster)"
    }
   ]
  },
  {
   "title": "Node selector for \"$flag\"",
   "type": "text",
   "description": "https://kubernetes-sigs.github.io/node-feature-discovery",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "options": {
    "content": "<pre>\nspec:\n  nodeSelector:\n    feature.node.kubernetes.io/cpu-cpuid.<span style=\"text-transform:uppercase;\">$flag</span>: 'true'\n</pre>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster \"$cluster\" details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Supported flags on cluster \"$cluster\"",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_labels{} * on (node) group_left sum(kube_node_labels{cluster=\"$cluster\"}) by (node)"
    }
   ]
  }
 ]
}