{
 "title": "aiops-tools-workshop",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "JupyterHub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jupyter Servers Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"aiops-tools-workshop\", pod=~'jupyterhub-nb-.*'})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'jupyterhub-[0-9]-.*',namespace='aiops-tools-workshop',container='',}) BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'jupyterhub-[0-9]-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'jupyterhub-[0-9]-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'jupyterhub-[0-9]-.*',namespace='aiops-tools-workshop'} ",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'jupyterhub-[0-9]-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'jupyterhub-[0-9]-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Cloudbeaver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'cloudbeaver-.*',namespace='aiops-tools-workshop',container='',}) BY (pod, namespace)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'cloudbeaver-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'cloudbeaver-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'cloudbeaver-.*',namespace='aiops-tools-workshop'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'cloudbeaver-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'cloudbeaver-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Dex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'dex-.*',namespace='aiops-tools-workshop',container='',})  BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'dex-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'dex-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'dex-.*',namespace='aiops-tools-workshop'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'dex-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'dex-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Superset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'superset-.*',namespace='aiops-tools-workshop',container='',}) BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'superset-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'superset-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'superset-.*',namespace='aiops-tools-workshop'} ",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'superset-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'superset-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Superset DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'supersetdb-.*',namespace='aiops-tools-workshop',container='',}) BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'supersetdb-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'supersetdb-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'supersetdb-.*',namespace='aiops-tools-workshop'} ",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'supersetdb-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'supersetdb-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Trino Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'trino-coordinator-.*',namespace='aiops-tools-workshop',container='',})  BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'trino-coordinator-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'trino-coordinator-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'trino-coordinator-.*',namespace='aiops-tools-workshop'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'trino-coordinator-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'trino-coordinator-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Trino DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'trino-db-.*',namespace='aiops-tools-workshop',container='',})  BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'trino-db-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'trino-db-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'trino-db-.*',namespace='aiops-tools-workshop'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'trino-db-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'trino-db-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  },
  { "title": "Trino Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'trino-worker-.*',namespace='aiops-tools-workshop',container='',}) BY (pod, namespace)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~'trino-worker-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~'trino-worker-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'trino-worker-.*',namespace='aiops-tools-workshop'} ",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~'trino-worker-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~'trino-worker-.*',namespace='aiops-tools-workshop'}) BY (pod, namespace)",
     "legendFormat": "Requests {{ pod }}"
    }
   ]
  }
 ]
}