{
 "title": "Operate First - Project Owner Groups, Projects, & Namespaces",
 "time": { "from": "now-4d", "to": "now" },
 "panels": [
  { "title": "Ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Projects per Product Owner Group, last 4 days, last",
   "type": "bargauge",
   "description": "Projects per Product Owner Group, last 4 days, last",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(k8s_resource_annotations_info{annotation_op1st_project_owner!=\"\"}) by (annotation_op1st_project_owner))",
     "legendFormat": "{{annotation_op1st_project_owner}}"
    }
   ]
  },
  { "title": "Last", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Project Owner Groups, last 4 days, last",
   "type": "stat",
   "description": "Project Owner Groups, last 4 days, last",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (annotation_op1st_project_owner) (k8s_resource_annotations_info{annotation_op1st_project_owner!=\"\"}))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Projects per Project Owner Groups",
   "type": "stat",
   "description": "Projects per Project Owner Groups",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (annotation_openshift_io_display_name) (k8s_resource_annotations_info{annotation_openshift_io_display_name!=\"\"})) / count(count by (annotation_op1st_project_owner) (k8s_resource_annotations_info{annotation_op1st_project_owner!=\"\"}))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Projects, last 4 days, last",
   "type": "stat",
   "description": "Projects, last 4 days, last",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (annotation_openshift_io_display_name) (k8s_resource_annotations_info{annotation_openshift_io_display_name!=\"\"}))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Namespaces per Project",
   "type": "stat",
   "description": "Namespaces per Project",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (k8s_resource_annotations_info{name!=\"\", annotation_openshift_io_display_name!=\"\"})) / count(count by (annotation_openshift_io_display_name) (k8s_resource_annotations_info{annotation_openshift_io_display_name!=\"\"}))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Namespaces, last 4 days, last",
   "type": "stat",
   "description": "Namespaces, last 4 days, last",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (k8s_resource_annotations_info{name!=\"\", annotation_openshift_io_display_name!=\"\"}))",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Operate First",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "### Operate First Community Metrics\n- smaug\n\n- last 4 days\n- currently only the last 2 days are available\n\n- Project User (Groups)\n- Projects ~ Namespaces\n- KPIs\n  - Projects per Project User (Group)\n    - last, min, max\n  - Namespaces per Projects\n    - last. min, max\n    - should be always 1 per definition\n  - Projects per Project User (Group) by Project User "
   }
  },
  {
   "title": "Min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Owner Groups, last 4 days, min",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "count(count by (annotation_op1st_project_owner) (k8s_resource_annotations_info{annotation_op1st_project_owner!=\"\"}))",
       "legendFormat": "Verbose"
      }
     ]
    },
    {
     "title": "Projects, last 4 days, min",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "count(count by (annotation_openshift_io_display_name) (k8s_resource_annotations_info{annotation_openshift_io_display_name!=\"\"}))",
       "legendFormat": "Verbose"
      }
     ]
    },
    {
     "title": "Namespaces, last 4 days, min",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "count(count by (name) (k8s_resource_annotations_info{name!=\"\", annotation_openshift_io_display_name!=\"\"}))",
       "legendFormat": "Verbose"
      }
     ]
    }
   ]
  },
  {
   "title": "Max",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Owner Groups, last 4 days, max",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count(count by (annotation_op1st_project_owner) (k8s_resource_annotations_info{annotation_op1st_project_owner!=\"\"}))",
       "legendFormat": "Verbose"
      }
     ]
    },
    {
     "title": "Projects, last 4 days, max",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count(count by (annotation_openshift_io_display_name) (k8s_resource_annotations_info{annotation_openshift_io_display_name!=\"\"}))",
       "legendFormat": "Verbose"
      }
     ]
    },
    {
     "title": "Namespaces, last 4 days, max",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count(count by (name) (k8s_resource_annotations_info{name!=\"\", annotation_openshift_io_display_name!=\"\"}))",
       "legendFormat": "Verbose"
      }
     ]
    }
   ]
  }
 ]
}