{
 "title": "Storage Overview by Namespace",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name, cluster)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "% of Free Space of Namespace",
   "type": "stat",
   "description": "Shows total free space left in the namespace",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"$namespace\"}) / sum(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Total Space on Cluster",
   "type": "stat",
   "description": "Available space and Total Capacity of cluster\n(These metrics are aggregated by querying Persistent Volumes.)",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Available Space"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Used vs Available Space (Cluster)",
   "type": "piechart",
   "description": "Used vs Available Space by cluster",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Used {{ namespace }}"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Available {{ namespace }}"
    }
   ]
  },
  {
   "title": "Used Space by Cluster",
   "type": "bargauge",
   "description": "Used space by cluster,\nThis is the same as the pie chart except in a different visualization",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Capacity/Total"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace",
   "type": "timeseries",
   "description": "A time series-graph which visualizes memory usage throughout time",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{namespace=\"$namespace\",container=\"\",pod!=\"\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Space on Namespace",
   "type": "stat",
   "description": "Available and total capacity by selected namespace. \n(These metrics are aggregated by querying Persistent Volumes.)\nAvailable: How much you space you have to your disposal\nTotal: Total capacity given to your project/namespace",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"$namespace\", cluster=\"$cluster\"})",
     "legendFormat": "Available Space"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Used vs Available Space (Namespace)",
   "type": "piechart",
   "description": "Used Vs Available by the specific namespace\nUsed: How much has been used\nAvailable: How much space you have left (to use)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\", cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "Used "
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Used Space by Namespace",
   "type": "bargauge",
   "description": "Used space by namespace\nThis is the same as the pie chart except in a different visualization",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Capacity/Total"
    }
   ]
  },
  {
   "title": "% of Free Space by PVC",
   "type": "table",
   "description": "Total percentage of space free on existing mounted PVC's\n(Note: Percentage of free space by PVC, note that PVC may show up or be removed. It depends if the PVC is bounded by a pod)",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod (Top 10)",
   "type": "piechart",
   "description": "This panel displays the top 10 pods which the most amount of memory by namespace",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (pod)(container_memory_working_set_bytes{container=\"\",pod!=\"\",namespace=\"$namespace\"})))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}