{
 "title": "VPA_RC_CPU_AND_MEMORY_OVERVIEW",
 "description": "This dashboard is created to display CPU/Memory consumption on the pods for the VPA Operator monitoring filtering by namespace and cluster. We can also observe the changes on resource request and limits when the AutoUpdate policy is applied.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU - Request-Limit-Usage",
   "type": "timeseries",
   "description": "This panel displays the CPU usage for each pod filtering by namespace and cluster.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Usage-{{pod}}"
    },
    {
     "expr": "kube_pod_resource_request{cluster=\"$cluster\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Requests-{{pod}}"
    },
    {
     "expr": "kube_pod_resource_limit{cluster=\"$cluster\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Limits-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory - Request-Limit-Usage",
   "type": "timeseries",
   "description": "This panel displays the Memory consumption for each pod filtering by namespace and cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pod:container_memory_usage_bytes:sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Usage-{{pod}}"
    },
    {
     "expr": "kube_pod_resource_request{cluster=\"$cluster\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Request-{{pod}}"
    },
    {
     "expr": "kube_pod_resource_limit{cluster=\"$cluster\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Limits-{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "description": "This panel displays the CPU usage for each pod filtering by namespace and cluster.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Usage-{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "description": "This panel displays the Memory consumption for each pod filtering by namespace and cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pod:container_memory_usage_bytes:sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Usage-{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Resource Limits",
   "type": "timeseries",
   "description": "This panel displays the CPU resource limit values of all pods in the filtered cluster over time. This is especially useful to track when the AutoUpdate policy of VPA updater comes into action and changes the CPU resource limit values.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_resource_limit{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", pod!~\".*cron.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory Resource Limits",
   "type": "timeseries",
   "description": "This panel displays the Memory resource limit values of all pods in the filtered cluster over time. This is especially useful to track when the AutoUpdate policy of VPA updater comes into action and changes the Memory resource limit values.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_resource_limit{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod!~\".*cron.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod CPU Resource Request",
   "type": "timeseries",
   "description": "This panel displays the CPU resource request values of all pods in the filtered cluster over time. This is especially useful to track when the AutoUpdate policy of VPA updater comes into action and changes the requested CPU values.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_pod_resource_request{cluster=\"$cluster\", namespace=\"$namespace\", pod!~\".*cron.*\", resource=\"cpu\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory Resource Request",
   "type": "timeseries",
   "description": "This panel displays the Memory resource request values of all pods in the filtered cluster over time. This is especially useful to track when the AutoUpdate policy of VPA updater comes into action and changes the requested Memory values.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_resource_request{pod!~\".*cron.*\", resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}