{
 "title": "JupyterHub - User Perspective",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "log_datasource", "label": "Datasource for logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "opf-jupyterhub,opf-jupyterhub-stage"
   },
   {
    "name": "account",
    "label": "JupyterHub user",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "account_substring",
    "query": "label_values(kube_pod_container_info{namespace=\"opf-jupyterhub\",pod=\"jupyterhub-nb-$account\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "\n![](https://avatars.githubusercontent.com/u/17927519?s=200&v=4)"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scalar((kube_pod_status_phase{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\",phase=\"Pending\"} or on() vector(0))*1) +\nscalar((kube_pod_status_phase{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\",phase=\"Running\"} or on() vector(0))*2) +\nscalar((kube_pod_status_phase{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\",phase=\"Failed\"} or on() vector(0))*3) + \nscalar((kube_pod_status_phase{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\",phase=\"Succeeded\"} or on() vector(0))*4) +\nscalar((kube_pod_status_phase{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\",phase=\"Unknown\"} or on() vector(0))*5)"
    }
   ]
  },
  {
   "title": "CPU % of limit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "repeat": "kubeflowPod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scalar(pod:container_cpu_usage:sum{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\"}) / scalar(kube_pod_resource_limit{resource=\"cpu\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory % of limit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(pod:container_memory_usage_bytes:sum{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\"}) / scalar(sum(kube_pod_resource_limit{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"}))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "PVC % of limit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scalar(kubelet_volume_stats_used_bytes{namespace=\"$namespace\",persistentvolumeclaim=\"jupyterhub-nb-$account-pvc\"}) / scalar(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\",persistentvolumeclaim=\"jupyterhub-nb-$account-pvc\"})"
    }
   ]
  },
  {
   "title": "Total CPU cores reserved and unused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(scalar(sum(kube_pod_resource_request{resource=\"cpu\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})) - scalar(pod:container_cpu_usage:sum{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\"} or on() vector(0))) / sum(node_cpu_info)"
    }
   ]
  },
  {
   "title": "Total memory reserved and unused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(scalar(sum(kube_pod_resource_request{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})) - scalar(pod:container_memory_usage_bytes:sum{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\"} or on() vector(0))) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  { "title": "Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU breakdown",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_resource_limit{resource=\"cpu\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory breakdown",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_resource_limit{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=\"jupyterhub-nb-$account\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "pod:container_memory_usage_bytes:sum{namespace=\"$namespace\",pod=\"jupyterhub-nb-$account\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "User pod logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"$namespace\"} | json | kubernetes_pod_name=\"jupyterhub-nb-$account\" | line_format \"{{.message}}\""
    }
   ]
  },
  {
   "title": "Hub log entries related to this account",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"$namespace\"} | json | kubernetes_pod_name=~\"jupyterhub-\\\\d+-.*\" | message=~\".*user/$account_substring.*\" | line_format \"{{.message}}\""
    }
   ]
  },
  { "title": "Events [WORK-IN-PROGRESS]", "type": "logs", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 } },
  { "title": "Spark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Stacked CPU usage per each node overlayed with total sum of memory limit and request",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_resource_limit{resource=\"cpu\", exported_namespace=\"$namespace\", exported_pod=~\"spark-cluster-$account-.*\"})",
     "legendFormat": "Total limit"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\", exported_namespace=\"$namespace\", exported_pod=~\"spark-cluster-$account-.*\"})",
     "legendFormat": "Total request"
    },
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\",pod=~\"spark-cluster-$account-.*\"} * on(pod) group_right kube_pod_labels{namespace=\"opf-jupyterhub\",pod=~\"spark-cluster-$account-.*\",label_radanalytics_io_podType!=\"\"}",
     "legendFormat": "Usage: {{label_radanalytics_io_podType}}"
    }
   ]
  },
  {
   "title": "Memory breakdown",
   "type": "graph",
   "description": "Stacked memory usage per each node overlayed with total sum of memory limit and request",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_resource_limit{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=~\"spark-cluster-$account-.*\"})",
     "legendFormat": "Total limit"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"memory\", exported_namespace=\"$namespace\", exported_pod=~\"spark-cluster-$account-.*\"})",
     "legendFormat": "Total request"
    },
    {
     "expr": "pod:container_memory_usage_bytes:sum{namespace=\"$namespace\",pod=~\"spark-cluster-$account-.*\"} *\non(pod) group_right kube_pod_labels{namespace=\"opf-jupyterhub\",pod=~\"spark-cluster-$account-.*\",label_radanalytics_io_podType!=\"\"}",
     "legendFormat": "Usage: {{label_radanalytics_io_podType}}"
    }
   ]
  }
 ]
}