{
 "title": "Data Pipeline Resource Consumption",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Trino", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trino Coordinator Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"odh-trino\", pod=~'trino-coordinator-.*'})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_threads_max{namespace=\"odh-trino\", pod=~\"trino-coordinator-.*\", container=\"trino-coordinator\"} < 100000",
     "legendFormat": "Maximum Threads Allowed in Container"
    }
   ]
  },
  {
   "title": "Trino Worker Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"odh-trino\", pod=~'trino-worker-.*'})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(container_threads_max{namespace=\"odh-trino\", pod=~\"trino-worker-.*\", container=\"trino-worker\"}) < 100000",
     "legendFormat": "Maximum Threads Allowed in Container"
    }
   ]
  },
  {
   "title": "Trino Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~'trino-coordinator-.*',namespace='odh-trino',container='',}\n* on (pod) \nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{pod=~'trino-worker-.*',namespace='odh-trino',container='',}\n    * on (pod) \n    kube_pod_status_phase{namespace='odh-trino', phase='Running'}\n    ) \n\nBY (pod, namespace)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "avg(\n    \n    kube_pod_resource_limit{resource='memory',pod=~'trino-worker-.*',namespace='odh-trino'} \n    * on (pod) \n    kube_pod_status_phase{namespace='odh-trino', phase='Running'}\n    \n    ) ",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "avg(\n    kube_pod_resource_request{resource='memory',pod=~'trino-worker-.*',namespace='odh-trino'} \n    * on (pod) \n    kube_pod_status_phase{namespace='odh-trino', phase='Running'}\n    )",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "Trino CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'trino-coordinator-.*',namespace='odh-trino',container='',}\n* on (pod) \nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(\n    pod:container_cpu_usage:sum{pod=~'trino-worker-.*',namespace='odh-trino',container='',}\n    * on (pod) \n    kube_pod_status_phase{namespace='odh-trino', phase='Running'}\n    )\n\nBY (pod, namespace)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "avg(\n    \n    kube_pod_resource_limit{resource='cpu',pod=~'trino-worker-.*',namespace='odh-trino'} \n    * on (pod) \n    kube_pod_status_phase{namespace='odh-trino', phase='Running'}\n    \n    ) ",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "avg(\n    kube_pod_resource_request{resource='cpu',pod=~'trino-worker-.*',namespace='odh-trino'} \n    * on (pod) \n    kube_pod_status_phase{namespace='odh-trino', phase='Running'}\n    )",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "Trino DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~'trino-db-.*',namespace='odh-trino',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}\n",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "kube_pod_resource_limit{resource='memory',pod=~'trino-db-.*',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "kube_pod_resource_request{resource='memory',pod=~'trino-db-.*',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "Trino DB CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'trino-db-.*',namespace='odh-trino',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "kube_pod_resource_limit{resource='cpu',pod=~'trino-db-.*',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Limits {{ pod }}"
    },
    {
     "expr": "kube_pod_resource_request{resource='cpu',pod=~'trino-db-.*',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
     "legendFormat": "Requests {{pod}}"
    }
   ]
  },
  {
   "title": "Hive Metastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hive Metastore osc-datacommons-dev-0 Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~'hive-metastore-osc-datacommons-dev-0',namespace='odh-trino',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}\n",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'hive-metastore-osc-datacommons-dev-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}\n",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='memory',pod=~'hive-metastore-osc-datacommons-dev-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}\n",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Hive Metastore osc-datacommons-dev-0 CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'hive-metastore-osc-datacommons-dev-0',namespace='odh-trino',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'hive-metastore-osc-datacommons-dev-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'hive-metastore-osc-datacommons-dev-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Hive Metastore osc-datacommons-hive-ingest-0 Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~'hive-metastore-osc-datacommons-hive-ingest-0',namespace='odh-trino',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'hive-metastore-osc-datacommons-hive-ingest-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='memory',pod=~'hive-metastore-osc-datacommons-hive-ingest-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Hive Metastore hive-metastore-osc-datacommons-hive-ingest-0 CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'hive-metastore-osc-datacommons-hive-ingest-0',namespace='odh-trino',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'hive-metastore-osc-datacommons-hive-ingest-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'hive-metastore-osc-datacommons-hive-ingest-0',namespace='odh-trino'}\n* on (pod)\nkube_pod_status_phase{namespace='odh-trino', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AirFlow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Airflow Web Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~'airflow-web-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'airflow-web-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='memory',pod=~'airflow-web-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow Web CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'airflow-web-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'airflow-web-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'airflow-web-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow Sync Users Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~'airflow-sync-users-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'airflow-sync-users-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='memory',pod=~'airflow-sync-users-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow Sync Users CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'airflow-sync-users-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'airflow-sync-users-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'airflow-sync-users-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow Scheduler Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~'airflow-scheduler-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}\n",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'airflow-scheduler-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='memory',pod=~'airflow-scheduler-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}\n",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow Scheduler CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'airflow-scheduler-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'airflow-scheduler-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'airflow-scheduler-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow DB Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~'airflow-db-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'airflow-db-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='memory',pod=~'airflow-db-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "Airflow DB CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'airflow-db-.*',namespace='openmetadata',container='',}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'airflow-db-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'airflow-db-.*',namespace='openmetadata'}\n* on (pod)\nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "OM Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{pod=~'openmetadata-.*',namespace='openmetadata',container='',}\n    * on (pod) \n    kube_pod_status_phase{namespace='openmetadata', phase='Running'}\n    ) \n\nBY (pod, namespace)",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='memory',pod=~'openmetadata-.*',namespace='openmetadata'} \n* on (pod) \nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "avg(\n    kube_pod_resource_request{resource='memory',pod=~'openmetadata-.*',namespace='openmetadata'} \n    * on (pod) \n    kube_pod_status_phase{namespace='openmetadata', phase='Running'}\n    )",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    },
    {
     "title": "OM CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{pod=~'openmetadata-.*',namespace='openmetadata',container='',}\n* on (pod) \nkube_pod_status_phase{namespace='openmetadata', phase='Running'}\n",
       "legendFormat": "Usage {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_limit{resource='cpu',pod=~'openmetadata-.*',namespace='openmetadata'} \n* on (pod) \nkube_pod_status_phase{namespace='openmetadata', phase='Running'}",
       "legendFormat": "Limits {{ pod }}"
      },
      {
       "expr": "kube_pod_resource_request{resource='cpu',pod=~'openmetadata-.*',namespace='openmetadata'} \n* on (pod) \nkube_pod_status_phase{namespace='openmetadata', phase='Running'}\n",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}