{
 "title": "Landing Page",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Welcome page and links", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Welcome to Operate First Dashboard",
   "type": "text",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://github.com/operate-first/operate-first.github.io/raw/main/src/assets/opf-logo.png\" width=\"350px\">\n<h3>Welcome to the Operate First Grafana Dashboard</h2>\n<ul style=\"font-size: 1.2em\">\n  <li>Checkout out our <a href=\"https://www.operate-first.cloud/\">website</a></li>\n  <li>Browse our <a href=\"https://github.com/operate-first/apps\">GitHub repository</a></li>\n</ul>\n<h3>Want to contribute to the dashboards?</h2>\n<ul style=\"font-size: 1.2em\">\n  <li>Check our <a href=\"https://www.operate-first.cloud/apps/content/grafana/add_grafana_dashboard.html\">docs</a> to learn how to add your own dashboard</li>\n  <li>Join our <a href=\"https://join.slack.com/t/operatefirst/shared_invite/zt-o2gn4wn8-O39g7sthTAuPCvaCNRnLww\">Slack</a> if you have any questions or concerns \n</ul>\n<p style=\"font-size: 1.1em\">(<b>Note:</b> Grafana reboots frequently, please make sure to backup your dashboards. Check out our <a href=\"https://www.operate-first.cloud/apps/content/grafana/add_grafana_dashboard.html\">Grafana docs</a> for more information on how to backup your dashboard) </p>"
   }
  },
  { "title": "Featured Dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 } },
  { "title": "Cluster CPU Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Actual Cores In Use (Controller Nodes)",
   "type": "bargauge",
   "description": "Cores currently in use on each cluster (Controller nodes). This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"master\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "emea-balrog Actual Free Cores",
   "type": "piechart",
   "description": "Cores currently not in use on both the Controller and Worker nodes. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"master\"})) ",
     "legendFormat": "Controller Free Cores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"worker\"}))",
     "legendFormat": "Worker Free Nodes"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io=\"master\"}) ",
     "legendFormat": "Total ControllerCores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "Total Worker Cores"
    }
   ]
  },
  {
   "title": "Actual Cores In Use (Worker Nodes)",
   "type": "bargauge",
   "description": "Cores currently in use on each cluster (Worker nodes). This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"worker\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "moc-infra Actual Free Cores",
   "type": "piechart",
   "description": "Cores currently not in use on both the Controller and Worker nodes. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"master\"})) ",
     "legendFormat": "Controller Free Cores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"worker\"}))",
     "legendFormat": "Worker Free Nodes"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io=\"master\"}) ",
     "legendFormat": "Total ControllerCores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "Total Worker Cores"
    }
   ]
  },
  {
   "title": "moc-smaug Actual Free Cores",
   "type": "piechart",
   "description": "Cores currently not in use on both the Controller and Worker nodes. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"master\"})) ",
     "legendFormat": "Controller Free Cores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!~\".+\"}) - (sum(kube_pod_resource_request{resource=\"cpu\"} * on (node) group_left kube_node_role{role=\"worker\"}))",
     "legendFormat": "Worker Free Nodes"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io=\"master\"}) ",
     "legendFormat": "Total ControllerCores"
    },
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!~\".+\"})",
     "legendFormat": "Total Worker Cores"
    }
   ]
  },
  { "title": "Cluster Memory Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Actual Combined Used Memory (Controller Nodes)",
   "type": "bargauge",
   "description": "Memory currently in use on each cluster (Controller nodes). This does not take into account ResourceQuotas, rather -- it takes into account memory available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"master\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "emea-balrog Memory Overview",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"master\"}))",
     "legendFormat": "Controller Free Memory"
    },
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!~\"master\"}) - (sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"worker\"}))",
     "legendFormat": "Worker Free Memory"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io=\"master\"}",
     "legendFormat": "Controller Total Memory"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Worker Total Memory"
    }
   ]
  },
  {
   "title": "Actual Combined Used Memory (Worker Nodes)",
   "type": "bargauge",
   "description": "Memory currently in use on each cluster (Worker nodes). This does not take into account ResourceQuotas, rather -- it takes into account memory available for the scheduler to reserve for pods.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"worker\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "moc-infra Memory Overview ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"master\"}))",
     "legendFormat": "Controller Free Memory"
    },
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!~\"master\"}) - (sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"worker\"}))",
     "legendFormat": "Worker Free Memory"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io=\"master\"}",
     "legendFormat": "Controller Total Memory"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Worker Total Memory"
    }
   ]
  },
  {
   "title": "moc-smaug Memory Overview ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io=\"master\"}) - (sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"master\"}))",
     "legendFormat": "Controller Free Memory"
    },
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!~\"master\"}) - (sum(kube_pod_resource_request{resource=\"memory\"} * on (node) group_left kube_node_role{role=\"worker\"}))",
     "legendFormat": "Worker Free Memory"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io=\"master\"}",
     "legendFormat": "Controller Total Memory"
    },
    {
     "expr": "cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!~\".+\"}",
     "legendFormat": "Worker Total Memory"
    }
   ]
  },
  { "title": "Cluster Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Pods Aggregated by Phase (emea-balrog)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase == 1) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods Aggregated by Phase (moc-infra)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase == 1) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods Aggregated by Phase (moc-smaug)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase == 1) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Cluster Storage Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "PVC's by Namespace (emea-balrog)",
   "type": "piechart",
   "description": "This graph shows the sum of PVC storage requested by namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "PVC's by Namespace (moc-infra)",
   "type": "piechart",
   "description": "This graph shows the sum of PVC storage requested by namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "PVC's by Namespace (moc-smaug)",
   "type": "piechart",
   "description": "This graph shows the sum of PVC storage requested by namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}