{
 "title": "Cluster CPU Usage",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created{}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Schedulable CPU cores",
   "type": "stat",
   "description": "Total cpu cores available for user workload scheduling, master nodes are not included.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node!~\"os-ctrl.*\", prometheus_replica=\"prometheus-k8s-0\"})"
    }
   ]
  },
  {
   "title": "Total CPU requests from ResourceQuotas",
   "type": "stat",
   "description": "The total amount of cpu requests that have been requested by ResourceQuotas currently active.",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"hard\", resource=\"requests.cpu\", prometheus_replica=\"prometheus-k8s-0\"})"
    }
   ]
  },
  {
   "title": "Free Cores (Approx)",
   "type": "stat",
   "description": "Cores currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_capacity_cpu_cores{node!~\"os-ctrl.*\"}) - sum(kube_pod_resource_request{node!~\"os-ctrl.*\", resource=\"cpu\"}))/2"
    }
   ]
  },
  {
   "title": "Free Cores (Approx)",
   "type": "graph",
   "description": "Cores currently not in use. This does not take into account ResourceQuotas, rather -- it takes into account cores available for the scheduler to reserve for pods.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_node_status_capacity_cpu_cores{node!~\"os-ctrl.*\"}) - sum(kube_pod_resource_request{node!~\"os-ctrl.*\", resource=\"cpu\"}))/2"
    }
   ]
  },
  {
   "title": "Pod CPU Requested By Namespace",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of cpu being requested by pods per namespace. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_resource_request{resource=\"cpu\",  prometheus_replica=\"prometheus-k8s-1\"}) by (exported_namespace))",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "CPU Requests by ResourceQuotas",
   "type": "grafana-piechart-panel",
   "description": "This graph shows the sum of cpu being requested by resourcequotas. I.e. how much CPU can be requested per namespace in total.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"hard\", resource=\"requests.cpu\", prometheus_replica=\"prometheus-k8s-1\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total CPU Requests",
   "type": "gauge",
   "description": "Approximate CPU requests on each node by summing CPU requests on all PENDING and RUNNING pods.\n\n\nMaximum value is found by running: \n\nsum(kube_node_status_allocatable_cpu_cores{cluster=\"\", prometheus_replica=\"prometheus-k8s-1\"}) by (node)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(sum(sum(kube_pod_container_resource_requests_cpu_cores{prometheus_replica=\"prometheus-k8s-1\"}) by (namespace, pod, node) * on (pod, namespace) group_left()  (sum(kube_pod_status_phase{phase=~\"Pending|Running\", prometheus_replica=\"prometheus-k8s-1\"}) by (pod, namespace) == 1)) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage vs Requests for namespace: $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "namespace"
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\", prometheus_replica=\"prometheus-k8s-0\", exported_namespace=\"$namespace\"}) by (exported_namespace)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "namespace:kube_pod_container_resource_requests_memory_bytes:sum{namespace=\"$namespace\", pod=\"prometheus-k8s-0\"}",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}